export const calculators = [
  {
    id: "optimizacija-plocastog-materijala",
    path: "/optimizacija-plocastog-materijala",
    className: "bg-gray-600 px-7 py-2 text-white",
    label: "Optimizuj sečenje ploče",
    category: ["industrija"],
  },
  {
    id: "procenti",
    path: "/procenti",
    className: "bg-green-600 px-7 py-2 text-white",
    label: "Odredi procenat",
    category: ["matematika", "fizika"],
  },
  {
    id: "indeks-telesne-mase",
    path: "/indeks-telesne-mase",
    className: "bg-purple-900 px-7 py-2 text-white",
    label: "Izračunaj BMI",
    category: ["sport", "zdravlje"],
  },
  {
    id: "konverter-mernih-jedinica-za-masu",
    path: "/konverter-mernih-jedinica-za-masu",
    className: "bg-orange-400 px-7 py-2 text-white",
    label: "Konvertuj mase",
    category: ["matematika", "fizika"],
  },
  {
    id: "konverter-mernih-jedinica-za-duzinu",
    path: "/konverter-mernih-jedinica-za-duzinu",
    className: "bg-cyan-900 px-7 py-2 text-white",
    label: "Pretvori dužine",
    category: ["matematika", "fizika"],
  },
  {
    id: "kalkulator-kalorija",
    path: "/kalkulator-kalorija",
    className: "bg-teal-500 px-7 py-2 text-white",
    label: "Izbroj kalorije",
    category: ["sport", "zdravlje"],
  },
  {
    id: "kalkulator-poreza-za-frilensere",
    path: "/kalkulator-poreza-za-frilensere",
    className: "bg-cyan-600 px-7 py-2 text-white",
    label: "Porez za frilensere",
    category: "finansije",
  },
];
