export const namirnice = [
  {
    id: 1,
    name: "Jabuka",
    category: "Fruits",
    nutritional_values: {
      calories: 52,
      fat: 0.2,
      carbohydrates: 14,
      protein: 0.3,
      fiber: 2.4,
      sugars: 10.4,
    },
    unit: "100g",
  },
  {
    id: 2,
    name: "Banana",
    category: "Fruits",
    nutritional_values: {
      calories: 96,
      fat: 0.3,
      carbohydrates: 27,
      protein: 1.3,
      fiber: 2.6,
      sugars: 14.4,
    },
    unit: "100g",
  },
  {
    id: 3,
    name: "Pileća prsa",
    category: "Meat",
    nutritional_values: {
      calories: 165,
      fat: 3.6,
      carbohydrates: 0,
      protein: 31,
      fiber: 0,
      sugars: 0,
    },
    unit: "100g",
  },
  {
    id: 4,
    name: "Beli pirinač",
    category: "Grains",
    nutritional_values: {
      calories: 130,
      fat: 0.3,
      carbohydrates: 28,
      protein: 2.7,
      fiber: 0.4,
      sugars: 0.1,
    },
    unit: "100g",
  },
  {
    id: 5,
    name: "Brokoli",
    category: "Vegetables",
    nutritional_values: {
      calories: 55,
      fat: 0.6,
      carbohydrates: 11.1,
      protein: 3.7,
      fiber: 3.3,
      sugars: 2.2,
    },
    unit: "100g",
  },
  {
    id: 6,
    name: "Jaje",
    category: "Dairy & Eggs",
    nutritional_values: {
      calories: 155,
      fat: 11,
      carbohydrates: 1.1,
      protein: 13,
      fiber: 0,
      sugars: 1.1,
    },
    unit: "100g",
  },
  {
    id: 7,
    name: "Sir čedar",
    category: "Dairy & Eggs",
    nutritional_values: {
      calories: 402,
      fat: 33,
      carbohydrates: 1.3,
      protein: 25,
      fiber: 0,
      sugars: 0.5,
    },
    unit: "100g",
  },
  {
    id: 8,
    name: "Badem",
    category: "Nuts & Seeds",
    nutritional_values: {
      calories: 579,
      fat: 49,
      carbohydrates: 22,
      protein: 21,
      fiber: 12.5,
      sugars: 4.4,
    },
    unit: "100g",
  },
  {
    id: 9,
    name: "Losos",
    category: "Fish",
    nutritional_values: {
      calories: 208,
      fat: 13,
      carbohydrates: 0,
      protein: 20,
      fiber: 0,
      sugars: 0,
    },
    unit: "100g",
  },
  {
    id: 10,
    name: "Krompir",
    category: "Vegetables",
    nutritional_values: {
      calories: 77,
      fat: 0.1,
      carbohydrates: 17,
      protein: 2,
      fiber: 2.2,
      sugars: 0.8,
    },
    unit: "100g",
  },
  {
    id: 11,
    name: "Spanać",
    category: "Vegetables",
    nutritional_values: {
      calories: 23,
      fat: 0.4,
      carbohydrates: 3.6,
      protein: 2.9,
      fiber: 2.2,
      sugars: 0.4,
    },
    unit: "100g",
  },
  {
    id: 12,
    name: "Šargarepa",
    category: "Vegetables",
    nutritional_values: {
      calories: 41,
      fat: 0.2,
      carbohydrates: 9.6,
      protein: 0.9,
      fiber: 2.8,
      sugars: 4.7,
    },
    unit: "100g",
  },
  {
    id: 13,
    name: "Paradajz",
    category: "Vegetables",
    nutritional_values: {
      calories: 18,
      fat: 0.2,
      carbohydrates: 3.9,
      protein: 0.9,
      fiber: 1.2,
      sugars: 2.6,
    },
    unit: "100g",
  },
  {
    id: 14,
    name: "Puter od kikirikija",
    category: "Nuts & Seeds",
    nutritional_values: {
      calories: 588,
      fat: 50,
      carbohydrates: 20,
      protein: 25,
      fiber: 6,
      sugars: 9,
    },
    unit: "100g",
  },
  {
    id: 15,
    name: "Jagode",
    category: "Fruits",
    nutritional_values: {
      calories: 32,
      fat: 0.3,
      carbohydrates: 7.7,
      protein: 0.7,
      fiber: 2,
      sugars: 4.9,
    },
    unit: "100g",
  },
  {
    id: 16,
    name: "Borovnice",
    category: "Fruits",
    nutritional_values: {
      calories: 57,
      fat: 0.3,
      carbohydrates: 14,
      protein: 0.7,
      fiber: 2.4,
      sugars: 9.7,
    },
    unit: "100g",
  },
  {
    id: 17,
    name: "Avokado",
    category: "Fruits",
    nutritional_values: {
      calories: 160,
      fat: 15,
      carbohydrates: 9,
      protein: 2,
      fiber: 7,
      sugars: 0.7,
    },
    unit: "100g",
  },

  {
    id: 18,
    name: "Goveđi biftek",
    category: "Meat",
    nutritional_values: {
      calories: 250,
      fat: 15,
      carbohydrates: 0,
      protein: 26,
      fiber: 0,
      sugars: 0,
    },
    unit: "100g",
  },
  {
    id: 19,
    name: "Kinoa",
    category: "Grains",
    nutritional_values: {
      calories: 120,
      fat: 1.9,
      carbohydrates: 21.3,
      protein: 4.1,
      fiber: 2.8,
      sugars: 0.9,
    },
    unit: "100g",
  },
  {
    id: 20,
    name: "Tikvica",
    category: "Vegetables",
    nutritional_values: {
      calories: 17,
      fat: 0.3,
      carbohydrates: 3.1,
      protein: 1.2,
      fiber: 1,
      sugars: 1.9,
    },
    unit: "100g",
  },
  {
    id: 21,
    name: "Humus",
    category: "Legumes",
    nutritional_values: {
      calories: 166,
      fat: 9.6,
      carbohydrates: 14.3,
      protein: 7.9,
      fiber: 6,
      sugars: 0.3,
    },
    unit: "100g",
  },
  {
    id: 22,
    name: "Mango",
    category: "Fruits",
    nutritional_values: {
      calories: 60,
      fat: 0.4,
      carbohydrates: 15,
      protein: 0.8,
      fiber: 1.6,
      sugars: 13.7,
    },
    unit: "100g",
  },
  {
    id: 23,
    name: "Leblebija",
    category: "Legumes",
    nutritional_values: {
      calories: 164,
      fat: 2.6,
      carbohydrates: 27.4,
      protein: 8.9,
      fiber: 7.6,
      sugars: 4.8,
    },
    unit: "100g",
  },
  {
    id: 24,
    name: "Sladak krompir",
    category: "Vegetables",
    nutritional_values: {
      calories: 86,
      fat: 0.1,
      carbohydrates: 20.1,
      protein: 1.6,
      fiber: 3,
      sugars: 4.2,
    },
    unit: "100g",
  },
  {
    id: 25,
    name: "Seme bundeve",
    category: "Nuts & Seeds",
    nutritional_values: {
      calories: 559,
      fat: 49,
      carbohydrates: 15,
      protein: 30,
      fiber: 6,
      sugars: 1.4,
    },
    unit: "100g",
  },
  {
    id: 26,
    name: "Smuđ",
    category: "Fish",
    nutritional_values: {
      calories: 129,
      fat: 2.7,
      carbohydrates: 0,
      protein: 26,
      fiber: 0,
      sugars: 0,
    },
    unit: "100g",
  },
  {
    id: 27,
    name: "Kelj",
    category: "Vegetables",
    nutritional_values: {
      calories: 35,
      fat: 0.5,
      carbohydrates: 4.4,
      protein: 2.9,
      fiber: 1.6,
      sugars: 0.8,
    },
    unit: "100g",
  },
  {
    id: 28,
    name: "Maline",
    category: "Fruits",
    nutritional_values: {
      calories: 52,
      fat: 0.7,
      carbohydrates: 12,
      protein: 1.2,
      fiber: 6.5,
      sugars: 4.4,
    },
    unit: "100g",
  },
  {
    id: 29,
    name: "Karfiol",
    category: "Vegetables",
    nutritional_values: {
      calories: 25,
      fat: 0.3,
      carbohydrates: 5,
      protein: 2,
      fiber: 2,
      sugars: 1.9,
    },
    unit: "100g",
  },
  {
    id: 30,
    name: "Grčki jogurt",
    category: "Dairy & Eggs",
    nutritional_values: {
      calories: 59,
      fat: 0.4,
      carbohydrates: 3.6,
      protein: 10,
      fiber: 0,
      sugars: 3.2,
    },
    unit: "100g",
  },
  {
    id: 31,
    name: "Orah",
    category: "Nuts & Seeds",
    nutritional_values: {
      calories: 654,
      fat: 65,
      carbohydrates: 14,
      protein: 15,
      fiber: 6.7,
      sugars: 2.6,
    },
    unit: "100g",
  },
  {
    id: 32,
    name: "Čvarci",
    category: "Snacks",
    nutritional_values: {
      calories: 544,
      fat: 31,
      carbohydrates: 0,
      protein: 61,
      fiber: 0,
      sugars: 0,
    },
    unit: "100g",
  },
  {
    id: 33,
    name: "Kupus",
    category: "Vegetables",
    nutritional_values: {
      calories: 25,
      fat: 0.1,
      carbohydrates: 6,
      protein: 1.3,
      fiber: 2.5,
      sugars: 3.2,
    },
    unit: "100g",
  },
  {
    id: 34,
    name: "Crni pasulj",
    category: "Legumes",
    nutritional_values: {
      calories: 132,
      fat: 0.5,
      carbohydrates: 23.7,
      protein: 8.9,
      fiber: 8.3,
      sugars: 0.3,
    },
    unit: "100g",
  },
  {
    id: 35,
    name: "Škamp",
    category: "Seafood",
    nutritional_values: {
      calories: 99,
      fat: 0.3,
      carbohydrates: 0.2,
      protein: 24,
      fiber: 0,
      sugars: 0,
    },
    unit: "100g",
  },
  {
    id: 36,
    name: "Krastavac svež",
    category: "Vegetables",
    nutritional_values: {
      calories: 16,
      fat: 0.1,
      carbohydrates: 3.6,
      protein: 0.7,
      fiber: 0.5,
      sugars: 1.7,
    },
    unit: "100g",
  },
  {
    id: 37,
    name: "Kruška",
    category: "Fruits",
    nutritional_values: {
      calories: 57,
      fat: 0.1,
      carbohydrates: 15.2,
      protein: 0.4,
      fiber: 3.1,
      sugars: 9.8,
    },
    unit: "100g",
  },

  {
    id: 38,
    name: "Ćureća prsa",
    category: "Meat",
    nutritional_values: {
      calories: 135,
      fat: 1.2,
      carbohydrates: 0,
      protein: 30,
      fiber: 0,
      sugars: 0,
    },
    unit: "100g",
  },
  {
    id: 39,
    name: "Ovas",
    category: "Grains",
    nutritional_values: {
      calories: 389,
      fat: 7,
      carbohydrates: 66,
      protein: 17,
      fiber: 10.6,
      sugars: 0,
    },
    unit: "100g",
  },
  {
    id: 40,
    name: "Plavi patlidžan",
    category: "Vegetables",
    nutritional_values: {
      calories: 25,
      fat: 0.2,
      carbohydrates: 5.9,
      protein: 1,
      fiber: 3,
      sugars: 3.5,
    },
    unit: "100g",
  },
  {
    id: 41,
    name: "Zelena soja (Edamame)",
    category: "Legumes",
    nutritional_values: {
      calories: 122,
      fat: 5.2,
      carbohydrates: 9.9,
      protein: 11.9,
      fiber: 5.2,
      sugars: 2.2,
    },
    unit: "100g",
  },
  {
    id: 42,
    name: "Ananas",
    category: "Fruits",
    nutritional_values: {
      calories: 50,
      fat: 0.1,
      carbohydrates: 13,
      protein: 0.5,
      fiber: 1.4,
      sugars: 9.9,
    },
    unit: "100g",
  },
  {
    id: 43,
    name: "Crveni pasulj",
    category: "Legumes",
    nutritional_values: {
      calories: 127,
      fat: 0.5,
      carbohydrates: 22.8,
      protein: 8.7,
      fiber: 6.4,
      sugars: 0.3,
    },
    unit: "100g",
  },
  {
    id: 44,
    name: "Paškanat",
    category: "Vegetables",
    nutritional_values: {
      calories: 75,
      fat: 0.3,
      carbohydrates: 18,
      protein: 1.2,
      fiber: 4.9,
      sugars: 4.8,
    },
    unit: "100g",
  },
  {
    id: 45,
    name: "Seme suncokreta",
    category: "Nuts & Seeds",
    nutritional_values: {
      calories: 584,
      fat: 51,
      carbohydrates: 20,
      protein: 21,
      fiber: 8.6,
      sugars: 2.6,
    },
    unit: "100g",
  },
  {
    id: 46,
    name: "Bakalar",
    category: "Fish",
    nutritional_values: {
      calories: 82,
      fat: 0.7,
      carbohydrates: 0,
      protein: 18,
      fiber: 0,
      sugars: 0,
    },
    unit: "100g",
  },
  {
    id: 47,
    name: "Prokelj",
    category: "Vegetables",
    nutritional_values: {
      calories: 43,
      fat: 0.3,
      carbohydrates: 9,
      protein: 3.4,
      fiber: 3.8,
      sugars: 2.2,
    },
    unit: "100g",
  },
  {
    id: 48,
    name: "Borovnice",
    category: "Fruits",
    nutritional_values: {
      calories: 43,
      fat: 0.5,
      carbohydrates: 10,
      protein: 1.4,
      fiber: 5.3,
      sugars: 4.9,
    },
    unit: "100g",
  },
  {
    id: 49,
    name: "Praziluk",
    category: "Vegetables",
    nutritional_values: {
      calories: 61,
      fat: 0.3,
      carbohydrates: 14.2,
      protein: 1.5,
      fiber: 1.8,
      sugars: 3.9,
    },
    unit: "100g",
  },
  {
    id: 50,
    name: "Švabski sir",
    category: "Dairy & Eggs",
    nutritional_values: {
      calories: 98,
      fat: 4.3,
      carbohydrates: 3.4,
      protein: 11.1,
      fiber: 0,
      sugars: 2.7,
    },
    unit: "100g",
  },
  {
    id: 51,
    name: "Indijski orah",
    category: "Nuts & Seeds",
    nutritional_values: {
      calories: 553,
      fat: 44,
      carbohydrates: 30,
      protein: 18,
      fiber: 3.3,
      sugars: 5,
    },
    unit: "100g",
  },
  {
    id: 52,
    name: "Grašak",
    category: "Vegetables",
    nutritional_values: {
      calories: 81,
      fat: 0.4,
      carbohydrates: 14,
      protein: 5.4,
      fiber: 5.7,
      sugars: 5.7,
    },
    unit: "100g",
  },
  {
    id: 53,
    name: "Rotkvice",
    category: "Vegetables",
    nutritional_values: {
      calories: 16,
      fat: 0.1,
      carbohydrates: 3.4,
      protein: 0.7,
      fiber: 1.6,
      sugars: 1.9,
    },
    unit: "100g",
  },
  {
    id: 54,
    name: "Sardina",
    category: "Seafood",
    nutritional_values: {
      calories: 131,
      fat: 4.8,
      carbohydrates: 0,
      protein: 20,
      fiber: 0,
      sugars: 0,
    },
    unit: "100g",
  },
  {
    id: 55,
    name: "Celer",
    category: "Vegetables",
    nutritional_values: {
      calories: 14,
      fat: 0.2,
      carbohydrates: 3,
      protein: 0.7,
      fiber: 1.6,
      sugars: 1.3,
    },
    unit: "100g",
  },
  {
    id: 56,
    name: "Šljiva",
    category: "Fruits",
    nutritional_values: {
      calories: 46,
      fat: 0.3,
      carbohydrates: 11.4,
      protein: 0.7,
      fiber: 1.4,
      sugars: 9.9,
    },
    unit: "100g",
  },
  {
    id: 57,
    name: "Kajsija",
    category: "Fruits",
    nutritional_values: {
      calories: 48,
      fat: 0.4,
      carbohydrates: 11.1,
      protein: 1.4,
      fiber: 2,
      sugars: 9.2,
    },
    unit: "100g",
  },

  {
    id: 58,
    name: "Kukuruz šećerac",
    category: "Vegetables",
    nutritional_values: {
      calories: 86,
      fat: 1.2,
      carbohydrates: 19,
      protein: 3.2,
      fiber: 2.7,
      sugars: 6.3,
    },
    unit: "100g",
  },

  {
    id: 59,
    name: "Pistaći",
    category: "Nuts & Seeds",
    nutritional_values: {
      calories: 562,
      fat: 45,
      carbohydrates: 28,
      protein: 20,
      fiber: 10,
      sugars: 7.7,
    },
    unit: "100g",
  },

  {
    id: 60,
    name: "Sočivo",
    category: "Legumes",
    nutritional_values: {
      calories: 116,
      fat: 0.4,
      carbohydrates: 20,
      protein: 9,
      fiber: 7.9,
      sugars: 1.8,
    },
    unit: "100g",
  },

  {
    id: 61,
    name: "Cvekla",
    category: "Vegetables",
    nutritional_values: {
      calories: 43,
      fat: 0.2,
      carbohydrates: 9.6,
      protein: 1.6,
      fiber: 2.8,
      sugars: 6.8,
    },
    unit: "100g",
  },
  {
    id: 62,
    name: "Skuša",
    category: "Fish",
    nutritional_values: {
      calories: 205,
      fat: 13.9,
      carbohydrates: 0,
      protein: 18.6,
      fiber: 0,
      sugars: 0,
    },
    unit: "100g",
  },

  {
    id: 63,
    name: "Nar",
    category: "Fruits",
    nutritional_values: {
      calories: 83,
      fat: 1.2,
      carbohydrates: 18.7,
      protein: 1.7,
      fiber: 4,
      sugars: 13.7,
    },
    unit: "100g",
  },
  {
    id: 64,
    name: "Artičoka",
    category: "Vegetables",
    nutritional_values: {
      calories: 47,
      fat: 0.2,
      carbohydrates: 10.5,
      protein: 3.3,
      fiber: 5.4,
      sugars: 1,
    },
    unit: "100g",
  },
  {
    id: 65,
    name: "Bundeva",
    category: "Vegetables",
    nutritional_values: {
      calories: 34,
      fat: 0.3,
      carbohydrates: 7.8,
      protein: 0.9,
      fiber: 1.1,
      sugars: 3.3,
    },
    unit: "100g",
  },
  {
    id: 66,
    name: "Godži bobice",
    category: "Fruits",
    nutritional_values: {
      calories: 349,
      fat: 0.4,
      carbohydrates: 77,
      protein: 14,
      fiber: 13,
      sugars: 45,
    },
    unit: "100g",
  },
  {
    id: 67,
    name: "Tofu",
    category: "Legumes",
    nutritional_values: {
      calories: 76,
      fat: 4.8,
      carbohydrates: 1.9,
      protein: 8,
      fiber: 0.3,
      sugars: 0.6,
    },
    unit: "100g",
  },
  {
    id: 68,
    name: "Smokve",
    category: "Fruits",
    nutritional_values: {
      calories: 74,
      fat: 0.3,
      carbohydrates: 19.2,
      protein: 0.8,
      fiber: 2.9,
      sugars: 16.3,
    },
    unit: "100g",
  },

  {
    id: 69,
    name: "Jagnjetina",
    category: "Meat",
    nutritional_values: {
      calories: 294,
      fat: 23,
      carbohydrates: 0,
      protein: 20,
      fiber: 0,
      sugars: 0,
    },
    unit: "100g",
  },
  {
    id: 70,
    name: "Pačetina",
    category: "Meat",
    nutritional_values: {
      calories: 337,
      fat: 28,
      carbohydrates: 0,
      protein: 19,
      fiber: 0,
      sugars: 0,
    },
    unit: "100g",
  },
  {
    id: 71,
    name: "Mlevena junetina",
    category: "Meat",
    nutritional_values: {
      calories: 250,
      fat: 20,
      carbohydrates: 0,
      protein: 17,
      fiber: 0,
      sugars: 0,
    },
    unit: "100g",
  },
  {
    id: 72,
    name: "Svinjski file",
    category: "Meat",
    nutritional_values: {
      calories: 143,
      fat: 3.6,
      carbohydrates: 0,
      protein: 26,
      fiber: 0,
      sugars: 0,
    },
    unit: "100g",
  },
  {
    id: 73,
    name: "Divljač",
    category: "Meat",
    nutritional_values: {
      calories: 158,
      fat: 3.2,
      carbohydrates: 0,
      protein: 30,
      fiber: 0,
      sugars: 0,
    },
    unit: "100g",
  },
  {
    id: 74,
    name: "Bizon",
    category: "Meat",
    nutritional_values: {
      calories: 143,
      fat: 2.4,
      carbohydrates: 0,
      protein: 28,
      fiber: 0,
      sugars: 0,
    },
    unit: "100g",
  },
  {
    id: 75,
    name: "Teleći kotlet",
    category: "Meat",
    nutritional_values: {
      calories: 172,
      fat: 6.8,
      carbohydrates: 0,
      protein: 25,
      fiber: 0,
      sugars: 0,
    },
    unit: "100g",
  },
  {
    id: 76,
    name: "Goveđa džigerica",
    category: "Meat",
    nutritional_values: {
      calories: 135,
      fat: 3.6,
      carbohydrates: 3.8,
      protein: 20.4,
      fiber: 0,
      sugars: 0,
    },
    unit: "100g",
  },
  {
    id: 77,
    name: "Svinjski paumflek (potrbušina)",
    category: "Meat",
    nutritional_values: {
      calories: 518,
      fat: 53,
      carbohydrates: 0,
      protein: 9.3,
      fiber: 0,
      sugars: 0,
    },
    unit: "100g",
  },
  {
    id: 78,
    name: "Prepelica",
    category: "Meat",
    nutritional_values: {
      calories: 134,
      fat: 5,
      carbohydrates: 0,
      protein: 21,
      fiber: 0,
      sugars: 0,
    },
    unit: "100g",
  },
  {
    id: 79,
    name: "Guska",
    category: "Meat",
    nutritional_values: {
      calories: 305,
      fat: 28,
      carbohydrates: 0,
      protein: 16,
      fiber: 0,
      sugars: 0,
    },
    unit: "100g",
  },
  {
    id: 80,
    name: "Zečetina",
    category: "Meat",
    nutritional_values: {
      calories: 173,
      fat: 8,
      carbohydrates: 0,
      protein: 25,
      fiber: 0,
      sugars: 0,
    },
    unit: "100g",
  },
  {
    id: 81,
    name: "Svinjska kobasica (sveža)",
    category: "Meat",
    nutritional_values: {
      calories: 455,
      fat: 38,
      carbohydrates: 1.7,
      protein: 25,
      fiber: 0,
      sugars: 0.5,
    },
    unit: "100g",
  },
  {
    id: 82,
    name: "Šunka",
    category: "Meat",
    nutritional_values: {
      calories: 145,
      fat: 5,
      carbohydrates: 1.5,
      protein: 21,
      fiber: 0,
      sugars: 1.3,
    },
    unit: "100g",
  },
  {
    id: 83,
    name: "Goveđe suvo meso",
    category: "Meat",
    nutritional_values: {
      calories: 410,
      fat: 22,
      carbohydrates: 10,
      protein: 33,
      fiber: 0,
      sugars: 8,
    },
    unit: "100g",
  },
  {
    id: 84,
    name: "Fazan",
    category: "Meat",
    nutritional_values: {
      calories: 133,
      fat: 2.9,
      carbohydrates: 0,
      protein: 25,
      fiber: 0,
      sugars: 0,
    },
    unit: "100g",
  },
  {
    id: 85,
    name: "Pileći batak",
    category: "Meat",
    nutritional_values: {
      calories: 209,
      fat: 12,
      carbohydrates: 0,
      protein: 23,
      fiber: 0,
      sugars: 0,
    },
    unit: "100g",
  },
  {
    id: 86,
    name: "Kobasica",
    category: "Meat",
    nutritional_values: {
      calories: 301,
      fat: 25,
      carbohydrates: 2.5,
      protein: 16,
      fiber: 0,
      sugars: 1.2,
    },
    unit: "100g",
  },
  {
    id: 87,
    name: "Ribeye šnicla",
    category: "Meat",
    nutritional_values: {
      calories: 291,
      fat: 22,
      carbohydrates: 0,
      protein: 24,
      fiber: 0,
      sugars: 0,
    },
    unit: "100g",
  },
  {
    id: 88,
    name: "Suvo grožđe",
    category: "Fruits",
    nutritional_values: {
      calories: 299,
      fat: 0.5,
      carbohydrates: 79.2,
      protein: 3.1,
      fiber: 3.7,
      sugars: 59.2,
    },
    unit: "100g",
  },
  {
    id: 89,
    name: "Suve brusnice",
    category: "Fruits",
    nutritional_values: {
      calories: 325,
      fat: 1.1,
      carbohydrates: 83.3,
      protein: 0.4,
      fiber: 5.4,
      sugars: 65.3,
    },
    unit: "100g",
  },
  {
    id: 84,
    name: "Sveže brusnice",
    category: "Fruits",
    nutritional_values: {
      calories: 46,
      fat: 0.1,
      carbohydrates: 12,
      protein: 0.4,
      fiber: 4.1,
      sugars: 4.0,
    },
    unit: "100g",
  },
  {
    id: 85,
    name: "Slanina",
    category: "Meat",
    nutritional_values: {
      calories: 541,
      fat: 42,
      carbohydrates: 1.4,
      protein: 37,
      fiber: 0,
      sugars: 0.4,
    },
    unit: "100g",
  },
  {
    id: 86,
    name: "Pileća džigerica",
    category: "Meat",
    nutritional_values: {
      calories: 167,
      fat: 4.8,
      carbohydrates: 0.9,
      protein: 28,
      fiber: 0,
      sugars: 0.2,
    },
    unit: "100g",
  },
];
